Initial Entities set-up
davivieira/kuburger pull request #1
Opened 2019-01-12 17:55 UTC by davivieira

2019-01-13 18:51 UTC, emprestes requested changes

2019-01-13 18:51 UTC, emprestes commented on .gitignore
> +
Nice to have `target` and `bin` folder included.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Address.java
> +public class Address {
Because it is a model object (State Full), it is interesting to have Serializable (with serialVersionUID) and Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Address.java
> +    private short number;
Should be more interesting work with Wrapper object of `short` (Short)

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Address.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Address.java
> +    public String getStreetName() {
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Burger.java
> +public class Burger extends Product {
Please, considering AbstractProduct class (package level) to `extend` and Product as an interface (focus on flexibility).

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Burger.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Burger.java
> +    private String name;
Every product has a name, hasn't it?

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Burger.java
> +    public String getName() {
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Client.java
> +    public String getName() {
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Client.java
> +    private List<Address> addresses = new ArrayList<>();
Should be `final`, shouldn't it?

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Contact.java
> +    private int phoneNumber;
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Delivery.java
> +    public Order getOrder() {
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Order.java
> +    public List<Product> getProducts() {
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/OrderStatus.java
> +        return code;
I don't have sure, but I think you could try return `super.toString()` instead to use `code` field. `code`in this case become unuseful.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Payment.java
> +    public Order getOrder() {
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Product.java
> +    public double getPrice() {
Please, use Lombok framework for getters and setters.
https://projectlombok.org/features/GetterSetter

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Product.java
> +public abstract class Product {
Could be called `AbstractProduct`.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Burger.java
> +public class Burger extends Product {
Because it is a model object (State Full), it is interesting to have Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Client.java
> +public class Client {
Because it is a model object (State Full), it is interesting to have Serializable (with serialVersionUID) and Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Contact.java
> +public class Contact {
Because it is a model object (State Full), it is interesting to have Serializable (with serialVersionUID) and Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Delivery.java
> +public class Delivery {
Because it is a model object (State Full), it is interesting to have Serializable (with serialVersionUID) and Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Order.java
> +public class Order {
Because it is a model object (State Full), it is interesting to have Serializable (with serialVersionUID) and Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Payment.java
> +public class Payment {
Because it is a model object (State Full), it is interesting to have Serializable (with serialVersionUID) and Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Product.java
> +public abstract class Product {
Because it is a model object (State Full), it is interesting to have Serializable (with serialVersionUID) and Comparable behaviours implemented.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Client.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Contact.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Delivery.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Order.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Payment.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Product.java
> +}
`equals`, `hashCode` and `toString` implementations missing.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Contact.java
> +    private int phoneNumber;
Should be more interesting work with Wrapper object of `int` (Integer)

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Order.java
> +    private int id;
Should be more interesting work with Wrapper object of `int` (Long)

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Order.java
> +    private double amount;
Should be more interesting work with Wrapper object of `double` (Double)

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Order.java
> +    public double calculateAmount() {
Should be more interesting work with Wrapper object of `double` (Double)

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Payment.java
> +    private int id;
Should be more interesting work with Wrapper object of `int` (Long)

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Product.java
> +    private int id;
Should be more interesting work with Wrapper object of `int` (Long)

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/PaymentStatus.java
> +        return code;
I don't have sure, but I think you could try return `super.toString()` instead to use `code` field. `code`in this case become unuseful.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Burger.java
> +    private String name;
Maybe a `description` would be necessary here.

2019-01-13 18:51 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Client.java
> +    private List<Contact> contacts;
contact list needs initialization as well.

2019-01-13 21:23 UTC, davivieira commented on src/main/java/com/delivery/kuburger/entity/PaymentStatus.java
> +        return code;
I was thinking about `code` field for storing it in DB, and the value for displaying purposes.

2019-01-13 21:26 UTC, davivieira commented on src/main/java/com/delivery/kuburger/entity/Burger.java
> +public class Burger extends Product {
What's the purpose of interface 'Product'? Which behaviors this interface would be able to add to those who implement it, for example?

2019-01-16 06:08 UTC, emprestes requested changes

2019-01-16 06:08 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Address.java
> +public class Address implements Serializable, Comparable {
`Comparable` interface is a generic interface. So, please, use `Comparable<Address>`

2019-01-16 06:08 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Address.java
> +    public boolean equals(Object o) {
Please, unit tests for it.
JUnit has an extra lib called `junit-addons` (https://mvnrepository.com/artifact/junit-addons/junit-addons/1.4). Please, use it for testing all `equals`, `compareTo` and `hashCode` methods

2019-01-16 06:08 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/PaymentStatus.java
> +        return code;
Ok. It will have the same behaviour using `return super.toString();`, I suppose.

2019-01-16 06:08 UTC, emprestes commented on kuburger.iml
> +    <orderEntry type="library" scope="PROVIDED" name="Maven: org.projectlombok:lombok:1.18.4" level="project" />
I believe this file doesn't need to be versioned by git.

2019-01-16 06:08 UTC, emprestes commented on src/main/java/com/delivery/kuburger/entity/Product.java
> +}
Where is `toString` method implementation?

2019-01-24 21:52 UTC, davivieira commented
@emprestes temos testes!

2019-02-06 12:22 UTC, emprestes approved these changes

2019-02-06 12:23 UTC, merged